### PR TITLE
Make 4-player chess app responsive and refactor chess piece mechanics

### PR DESCRIPTION
**Pull request by ThePhoenix08**
### **Description**  
This pull request focuses on making the 4-player chess app responsive. It addresses the core issue of ensuring the chessboard, player indicators, and modal adapt to various screen sizes, improving the user experience across devices.
Issue: responsive #2 

### Summary:
- [ ] Bug Fix 🐛
- [x] New Feature ✨
- [ ] Custom 🔧

---

### ✨ New Feature:

- **Feature Added**: Responsiveness for the 4-player chess app.  
- **Reason for Feature**: The app lacked responsiveness, making it unsuitable for use on smaller screens. This update improves accessibility across devices.
- **Implementation Details**: 
  - Chess Grid Responsiveness:
Used CSS variables, calc(), var(), and vw units to make the grid dynamic.
  - Player Turn Indicators:
Replaced absolute-positioned chips with player panels surrounding the chessboard.
Hoisted current player state, interaction mode and logic into context with a provider for better state management.
  - Chess Piece Movement Mechanics:
Refactored and reimplemented the drag-and-drop mechanics to account for dynamic screen sizes using getBoundingClientRect().
Introduced playerState and an interactionMode state, allowing users to toggle between select-move and drag-and-drop methods.
Chess pieces now hide(visibility: hidden) when outside the valid chessboard
  - Modal Responsiveness:
Adjusted modal CSS for better scaling on smaller screens while preserving the original design aesthetic.

---

### **Additional Context**  
- Manual Testing: I’ve verified functionality manually, ensuring:
The chess grid adapts to various screen sizes.
Player indicators render correctly and are functional.
Chess piece movement works smoothly in both interaction modes.
Modal layouts display appropriately on different devices.
Documentation: Added comments for new logic and components.
- Chessboard and Player turn indicators
https://drive.google.com/file/d/1KyB3YoI1YYAzqyeDvHk0TKVMzzCcjFwJ/view?usp=drive_link
- Modal
Screenshot 2024-12-03 211601
Screenshot 2024-12-03 211517

---

### **Open Source Programs**
Yes, I am part of KWoC 2024 as student contributor and I am doing this PR under the program.

---

### ✅ Checklist:

- [x] My code adheres to the code style of this project.
- [ ] I have run the appropriate tests for this change.
- [x] I have updated the documentation (if needed).
- [x] My PR references any relevant issues (if applicable).
- [ ] Breaking changes?

### CODE REVIEW

**Review by prrockzed — APPROVED** [review]
Good work. I will be merging the changes

**Comment by prrockzed** [comment]
Hey I noticed there are some css problems. For instance, The players name bar should be aligned with the board(that is, they shouldn't go out from the board), and there should be some padding in the top and bottom of the board, for nice viewing.
Also, why would you give an option to select first if the player wants to drag and drop or just click on the squares to move the pieces. I think the players should do whatever they want without first choosing on how they want to play.. It creates more problems. Please remove this functionality of choosing on how the players will play. The player should have the option to drag-drop/clicking on squares without choosing an option.

**Comment by prrockzed** [comment]
Hey! Sorry to respond so late. Great work.
Just some small css changes needed. Would be great if you can align the nameplate with the board's sides, and give some padding between the board and the namplate(for all 4 nameplates)

Screenshot 2024-12-11 at 12 44 54 AM

**Comment by ThePhoenix08** [comment]
Hi, I have made the requested changes.
- added 10px gap between board and nameplates ( let me know if its good, or you want it to be reduced/increased )
- reduced internal padding of nameplates so now the nameplates' width aligns with the board width

Let me know if you need any further modifications.
Below are screenshots attached of the updated ui, you can also live test the updated ui here: https://thephoenix08.github.io/chessed/

Screenshots for how it looks on both Desktop and Mobile Phones
- Desktops: 
localhost_3000_chessed(Nest Hub Max) (1)

- Mobile Screen
localhost_3000_chessed(iPhone SE) (1)

**Pull request merged**
